###
# GET the Assets data 
GET http://localhost:4004/odata/v4/enterprise/Assets
###
# get employee datails 
GET http://localhost:4004/odata/v4/enterprise/employee
###
#create the data 
#BOTH ALSO TO BE CREATED 
###
#check the maintenance and retired 
POST http://localhost:4004/odata/v4/enterprise/Assets
Content-Type: application/json

{
  "name":"Laptop",
  "type":"Electronics",
  "serialNumber": "SN1001",
  "purchaseDate": "2024-01-10",
  "value": 75000,
  "status": "active",
  "location": "Chennai"
}

###
POST http://localhost:4004/odata/v4/enterprise/employee
Content-Type: application/json

{
  "name": "Mithun",
  "email": "mithun@example.com",
  "role":"employee"
}

###
### 3. Assign Asset (Valid)
POST http://localhost:4004/odata/v4/enterprise/assignment
Content-Type: application/json

{
    "asset":{
        "ID":"550e8400-e29b-41d4-a716-446655440007"
    },
    "employee":{
        "ID":"550e8400-e29b-41d4-a716-446655440012"
    },
    "assignedOn":"2026-06-16"
}

###
GET http://localhost:4004/odata/v4/enterprise/assignment
###
GET http://localhost:4004/odata/v4/enterprise/maintenance

###
POST http://localhost:4004/odata/v4/enterprise/maintenance
Content-Type: application/json

{
  "asset_ID": "550e8400-e29b-41d4-a716-446655440009",
  "issue": "damaged some parts",
  "status": "InProgress",
  "cost": 1000
}
###
PATCH http://localhost:4004/odata/v4/enterprise/maintenance(600b2375-a412-481b-8dc8-b51210ba97ae)
Content-Type: application/json

{
  "status": "Completed"
}

### 
# this should be the request for the product and then approve by the manager 
POST  http://localhost:4004/odata/v4/enterprise/AssetRequests
Content-Type: application/json

{
  "assetName":"switch",
  "type":"Electronic",
  "requestedBy":{

"ID": "550e8400-e29b-41d4-a716-446655440016"
  },
  "status":"pending"
}

###
#get the aprove or reject or pending 
GET http://localhost:4004/odata/v4/enterprise/AssetRequests

###
#post the role based for approval 
POST http://localhost:4004/odata/v4/enterprise/employee
Content-Type: application/json

{
  "name":"mithun manager",
  "email":"mithunraj@gmail.com",
  "role":"Manager"
}
###


POST http://localhost:4004/odata/v4/enterprise/AssetRequests
Content-Type: application/json  

{
  "assetName":"printer",
  "type":"Electronics",
  "requestedBy":{
    "ID":"550e8400-e29b-41d4-a716-446655440012"
  }
}

###
## this api is used to approve the requested order 
PATCH http://localhost:4004/odata/v4/enterprise/AssetRequests(4046a843-8c36-48af-98f0-7a03ce63e03a)
Content-Type: application/json

{
  "status": "Approved",
  "approvedBy_ID": "c3bf4239-e948-4ac7-b737-db83d8e90603"
}

###

### Check updated data
GET http://localhost:4004/odata/v4/enterprise/AssetRequests(ID=66f5345e-3a24-4f64-8d5e-f94d8807b492,IsActiveEntity=true)

### 
GET http://localhost:4004/odata/v4/enterprise/AssetRequests